### ISSUE TITLE
Model not configured

### ISSUE THREAD

**Issue by volkanunsal** [microsoft/genaiscript#1328]
Running into this issue:

```
 large: anthropic_bedrock:us.anthropic.claude-3-7-sonnet-20250219-v1:0 (config)
 small: anthropic_bedrock:us.anthropic.claude-3-5-sonnet-20241022-v2:0 (config)
 vision: openai:gpt-4o (default)
 vision_small: openai:gpt-4o-mini (default)
 embeddings: openai:text-embedding-3-small (default)
 reasoning: openai:o1 (default)
 reasoning_small: openai:o1-mini (default)
 transcription: openai:whisper-1 (default)
 speech: openai:tts-1 (default)
 image: openai:dall-e-3 (default)
 long: large (default)
 agent: large (default)
 memory: small (default)
 classify: small (default)
 summarize: small (default)
 cast: small (default)
 ocr: vision_small (default)
LLM provider not configured for 'large' (see https://microsoft.github.io/genaiscript/getting-started/configuration/)
```

I configured my model in `genaiscript.config.yml` file.

```yml
envFile:
  - /Users/newuser/.env.genaiscript
  - /Users/newuser/.aws/credentials
modelAliases:
  small: anthropic_bedrock:us.anthropic.claude-3-5-sonnet-20241022-v2:0
  large: anthropic_bedrock:us.anthropic.claude-3-7-sonnet-20250219-v1:0

```
